import type { BroadcastSettings } from "./types.js";

export const initialBroadcastSettings: BroadcastSettings = {
  videoCodec: "H.265",
  videoHardware: "off" as const,
  autoResumeOnLaunch: false,
  profile: "High Profile",
  level: "5.1",
  preset: 18,
  width: 3840,
  height: 2160,
  dimensionsLocked: true,
  frameRate: "23.976 fps",
  deinterlace: false,
  fieldOrder: "progressive",
  gopSize: 48,
  bFrames: 2,
  closedGop: true,
  rateControl: "CBR",
  targetBitrate: 18,
  maxBitrate: 18,
  bufferSize: 36_000,
  crf: 18,
  audioCodec: "AAC-LC",
  sampleRate: "48000 Hz",
  channels: "Stereo (L/R)",
  audioBitrate: 320,
  loudnessNormalizationEnabled: false,
  loudnessTargetLufs: -23,
  audioTracksEnabled: false,
  audioTrackDirectory: "",
  audioOriginalLanguage: "rus",
  audioOriginalLabel: "orig",
  streamingEnabled: true,
  protocol: "SRT",
  serverUrl: "srt://stream.nexusbroadcast.live:4223",
  streamKey: "gruber-live-production-key",
  latency: "Low Latency",
  udpHost: "239.10.10.10",
  udpPort: 5000,
  udpPacketSize: 1316,
  udpTtl: 16,
  udpLocalAddress: "",
  udpServiceName: "FluxIO",
  udpServiceId: 1,
  udpProviderName: "FluxIO",
  udpVideoPid: 256,
  udpAudioPid: 257,
  udpServiceType: "digital_tv",
  udpPcrPeriodMs: 20,
  udpTransportBitrate: 0,
  srtHost: "127.0.0.1",
  srtPort: 9000,
  srtMode: "caller",
  srtLatencyMs: 120,
  srtPassphrase: "",
  srtStreamId: "",
  rtmpServerUrl: "rtmp://127.0.0.1/live",
  rtmpStreamKey: "gruber-live",
  subtitleOutputMode: "Burn-in",
  subtitlePid: 288,
  subtitleLanguage: "rus",
  subtitleType: "Normal",
  subtitleFontFamily: "Sans",
  subtitleFontSize: 48,
  subtitleBottomMargin: 72,
  subtitleOutline: true,
  subtitleMaxColours: 16,
  subtitleBitrateKbps: 128,
  subtitlePtsOffsetMs: 0,
  ageTitleDurationSeconds: 10,
  logoEnabled: false,
  logoPath: "",
  logoLoop: true,
  logoPosition: "top-right",
  logoWidthPercent: 15,
  logoMargin: 32,
  logoOpacity: 1,
  repeatSchedule: false,
  scte35PlanningEnabled: false,
  scte35Command: "time_signal + segmentation_descriptor",
  scte35Owner: "Provider",
  scte35Pid: 500,
  scte35PreRollMs: 4_000,
  scte35DefaultEventId: 1,
  scte35DefaultBreakDuration: 120,
  scte35UpidType: "Ad-ID",
  scte35DefaultUpid: "",
  scte35LoopEventStrategy: "Increment each loop",
};
