import type { MediaAsset } from "./types";
import { mediaPath } from "./runtime";

export const initialAssets: MediaAsset[] = [
  {
    id: "forest",
    name: "A001_C012_1024_A.mov",
    duration: "00:04:12:00",
    durationSeconds: 252,
    codec: "ProRes 422 HQ",
    codecFamily: "PRRes",
    codecProfile: "422HQ",
    resolution: "3840×2160",
    fps: "23.98 fps",
    bitrate: "220 Mbps",
    size: "12.4 GB",
    status: "analyzed",
    progress: 100,
    preview: mediaPath("forest.png"),
    filePath: "/MEDIA/CARD_A/A001_C012_1024_A.mov",
    colorSpace: "Rec. 709",
    audio: "PCM 48kHz 24b",
    sha256: "b18a0e...9c22",
    scheduleType: "clip",
    declaredDurationSeconds: 252,
    ageTitle: { durationSeconds: 10, enabled: true, text: "16+" },
    itemLogo: {
      enabled: true,
      loop: true,
      filePath: "/MEDIA/BRANDING/channel.png",
      margin: 24,
      opacity: 1,
      position: "top-right",
      widthPercent: 12,
    },
  },
  {
    id: "interview",
    name: "Interview_President_Take02.mp4",
    duration: "01:14:05:00",
    durationSeconds: 4_445,
    codec: "H.264 (AVC)",
    codecFamily: "H.264",
    codecProfile: "AVC",
    resolution: "1920×1080",
    fps: "29.97 fps",
    bitrate: "18 Mbps",
    size: "9.2 GB",
    status: "analyzed",
    progress: 100,
    preview: mediaPath("interview.png"),
    filePath: "/MEDIA/CARD_A/Interview_President_Take02.mp4",
    colorSpace: "Rec. 709",
    audio: "AAC 48kHz Stereo",
    sha256: "f82c31...117a",
    scheduleType: "movie",
    declaredDurationSeconds: 4_445,
    ageTitle: { durationSeconds: 10, enabled: true, text: "16+" },
  },
  {
    id: "production",
    name: "Promo_BehindTheScenes_03_RAW.mov",
    duration: "00:18:40:00",
    durationSeconds: 1_120,
    codec: "ProRes 4444",
    codecFamily: "PRRes",
    codecProfile: "4444",
    resolution: "3840×2160",
    fps: "23.98 fps",
    bitrate: "310 Mbps",
    size: "42.1 GB",
    status: "analyzed",
    progress: 85,
    preview: mediaPath("production.png"),
    filePath: "/MEDIA/CARD_A/Promo_BehindTheScenes_03_RAW.mov",
    colorSpace: "Rec. 709",
    audio: "PCM 48kHz 24b",
    sha256: "a3f9c2...d41e",
    scheduleType: "movie",
    declaredDurationSeconds: 1_120,
    itemLogo: {
      enabled: true,
      loop: true,
      filePath: "/MEDIA/BRANDING/channel.png",
      margin: 24,
      opacity: 1,
      position: "top-right",
      widthPercent: 12,
    },
  },
  {
    id: "reef",
    name: "GoPro_Undersea_Reef_HEVC.mp4",
    duration: "00:08:15:00",
    durationSeconds: 495,
    codec: "H.265 (HEVC)",
    codecFamily: "H.265",
    codecProfile: "HEVC",
    resolution: "3840×2160",
    fps: "60.00 fps",
    bitrate: "45 Mbps",
    size: "2.6 GB",
    status: "pending",
    progress: 20,
    preview: mediaPath("reef.png"),
    filePath: "/MEDIA/CARD_B/GoPro_Undersea_Reef_HEVC.mp4",
    colorSpace: "Rec. 2020",
    audio: "AAC 48kHz Stereo",
    sha256: "d72bc8...c020",
    scheduleType: "movie",
  },
  {
    id: "city",
    name: "Drone_Cityscape_Nightlapse_final.mp4",
    duration: "00:02:30:00",
    durationSeconds: 150,
    codec: "H.264 (AVC)",
    codecFamily: "H.264",
    codecProfile: "AVC",
    resolution: "1920×1080",
    fps: "30.00 fps",
    bitrate: "25 Mbps",
    size: "460 MB",
    status: "error",
    preview: mediaPath("city.png"),
    filePath: "/MEDIA/CARD_C/Drone_Cityscape_Nightlapse_final.mp4",
    colorSpace: "Rec. 709",
    audio: "No audio stream",
    sha256: "91dca6...02ae",
    scheduleType: "clip",
  },
];

export const additionalPlaylistAssets: MediaAsset[] = [
  {
    id: "event",
    name: "EventShow_MainStage_MultiCam.mov",
    duration: "00:52:18:00",
    durationSeconds: 3_138,
    codec: "ProRes 4444",
    codecFamily: "PRRes",
    codecProfile: "4444",
    resolution: "3840×2160",
    fps: "25.00 fps",
    bitrate: "280 Mbps",
    size: "68.5 GB",
    status: "queued",
    preview: mediaPath("reef.png"),
    filePath: "/MEDIA/RAID/EventShow_MainStage_MultiCam.mov",
    colorSpace: "Rec. 709",
    audio: "PCM 48kHz 24b",
    sha256: "ed2a01...765b",
  },
  {
    id: "desert",
    name: "DesertAerial_SunrisePass_4K.mp4",
    duration: "00:06:44:12",
    durationSeconds: 404,
    codec: "H.265 (HEVC)",
    codecFamily: "H.265",
    codecProfile: "HEVC",
    resolution: "3840×2160",
    fps: "23.98 fps",
    bitrate: "45 Mbps",
    size: "2.1 GB",
    status: "queued",
    preview: mediaPath("desert.png"),
    filePath: "/MEDIA/RAID/DesertAerial_SunrisePass_4K.mp4",
    colorSpace: "Rec. 2020",
    audio: "AAC 48kHz Stereo",
    sha256: "901fa2...c329",
  },
  {
    id: "night",
    name: "CityNight_TimeLapse_Final_v3.mp4",
    duration: "00:03:55:00",
    durationSeconds: 235,
    codec: "DNxHD 185x",
    codecFamily: "DNxHD",
    codecProfile: "185x",
    resolution: "1920×1080",
    fps: "25.00 fps",
    bitrate: "185 Mbps",
    size: "5.4 GB",
    status: "queued",
    preview: mediaPath("night.png"),
    filePath: "/MEDIA/RAID/CityNight_TimeLapse_Final_v3.mp4",
    colorSpace: "Rec. 709",
    audio: "PCM 48kHz 24b",
    sha256: "22b17d...9a31",
  },
  {
    id: "ocean",
    name: "OceanReef_Divemaster_POV.mov",
    duration: "00:14:20:08",
    durationSeconds: 860,
    codec: "ProRes 422",
    codecFamily: "PRRes",
    codecProfile: "422",
    resolution: "3840×2160",
    fps: "50.00 fps",
    bitrate: "160 Mbps",
    size: "17.2 GB",
    status: "queued",
    preview: mediaPath("ocean.png"),
    filePath: "/MEDIA/RAID/OceanReef_Divemaster_POV.mov",
    colorSpace: "Rec. 709",
    audio: "PCM 48kHz 24b",
    sha256: "f220c4...a1c8",
  },
  {
    id: "concert",
    name: "ConcertLive_MasterMix_5cam.mp4",
    duration: "01:32:00:00",
    durationSeconds: 5_520,
    codec: "H.264 (AVC)",
    codecFamily: "H.264",
    codecProfile: "AVC",
    resolution: "1920×1080",
    fps: "25.00 fps",
    bitrate: "20 Mbps",
    size: "13.4 GB",
    status: "queued",
    preview: mediaPath("concert.png"),
    filePath: "/MEDIA/RAID/ConcertLive_MasterMix_5cam.mp4",
    colorSpace: "Rec. 709",
    audio: "AAC 48kHz Stereo",
    sha256: "820da4...4e8b",
  },
];
