import type {
  BroadcastSettings,
  EncodingJob,
  MediaAsset,
} from "./types";
import { mediaPath } from "./runtime";

export const initialAssets: MediaAsset[] = [
  {
    id: "forest",
    name: "A001_C012_1024_A.mov",
    duration: "00:04:12:00",
    durationSeconds: 252,
    codec: "ProRes 422 HQ",
    codecFamily: "PRRes",
    codecProfile: "422HQ",
    resolution: "3840×2160",
    fps: "23.98 fps",
    bitrate: "220 Mbps",
    size: "12.4 GB",
    status: "analyzed",
    progress: 100,
    preview: mediaPath("forest.png"),
    filePath: "/MEDIA/CARD_A/A001_C012_1024_A.mov",
    colorSpace: "Rec. 709",
    audio: "PCM 48kHz 24b",
    sha256: "b18a0e...9c22",
  },
  {
    id: "interview",
    name: "Interview_President_Take02.mp4",
    duration: "01:14:05:00",
    durationSeconds: 4_445,
    codec: "H.264 (AVC)",
    codecFamily: "H.264",
    codecProfile: "AVC",
    resolution: "1920×1080",
    fps: "29.97 fps",
    bitrate: "18 Mbps",
    size: "9.2 GB",
    status: "analyzed",
    progress: 100,
    preview: mediaPath("interview.png"),
    filePath: "/MEDIA/CARD_A/Interview_President_Take02.mp4",
    colorSpace: "Rec. 709",
    audio: "AAC 48kHz Stereo",
    sha256: "f82c31...117a",
  },
  {
    id: "production",
    name: "Promo_BehindTheScenes_03_RAW.mov",
    duration: "00:18:40:00",
    durationSeconds: 1_120,
    codec: "ProRes 4444",
    codecFamily: "PRRes",
    codecProfile: "4444",
    resolution: "3840×2160",
    fps: "23.98 fps",
    bitrate: "310 Mbps",
    size: "42.1 GB",
    status: "analyzed",
    progress: 85,
    preview: mediaPath("production.png"),
    filePath: "/MEDIA/CARD_A/Promo_BehindTheScenes_03_RAW.mov",
    colorSpace: "Rec. 709",
    audio: "PCM 48kHz 24b",
    sha256: "a3f9c2...d41e",
  },
  {
    id: "reef",
    name: "GoPro_Undersea_Reef_HEVC.mp4",
    duration: "00:08:15:00",
    durationSeconds: 495,
    codec: "H.265 (HEVC)",
    codecFamily: "H.265",
    codecProfile: "HEVC",
    resolution: "3840×2160",
    fps: "60.00 fps",
    bitrate: "45 Mbps",
    size: "2.6 GB",
    status: "pending",
    progress: 20,
    preview: mediaPath("reef.png"),
    filePath: "/MEDIA/CARD_B/GoPro_Undersea_Reef_HEVC.mp4",
    colorSpace: "Rec. 2020",
    audio: "AAC 48kHz Stereo",
    sha256: "d72bc8...c020",
  },
  {
    id: "city",
    name: "Drone_Cityscape_Nightlapse_final.mp4",
    duration: "00:02:30:00",
    durationSeconds: 150,
    codec: "H.264 (AVC)",
    codecFamily: "H.264",
    codecProfile: "AVC",
    resolution: "1920×1080",
    fps: "30.00 fps",
    bitrate: "25 Mbps",
    size: "460 MB",
    status: "error",
    preview: mediaPath("city.png"),
    filePath: "/MEDIA/CARD_C/Drone_Cityscape_Nightlapse_final.mp4",
    colorSpace: "Rec. 709",
    audio: "No audio stream",
    sha256: "91dca6...02ae",
  },
];

export const additionalPlaylistAssets: MediaAsset[] = [
  {
    id: "event",
    name: "EventShow_MainStage_MultiCam.mov",
    duration: "00:52:18:00",
    durationSeconds: 3_138,
    codec: "ProRes 4444",
    codecFamily: "PRRes",
    codecProfile: "4444",
    resolution: "3840×2160",
    fps: "25.00 fps",
    bitrate: "280 Mbps",
    size: "68.5 GB",
    status: "queued",
    preview: mediaPath("reef.png"),
    filePath: "/MEDIA/RAID/EventShow_MainStage_MultiCam.mov",
    colorSpace: "Rec. 709",
    audio: "PCM 48kHz 24b",
    sha256: "ed2a01...765b",
  },
  {
    id: "desert",
    name: "DesertAerial_SunrisePass_4K.mp4",
    duration: "00:06:44:12",
    durationSeconds: 404,
    codec: "H.265 (HEVC)",
    codecFamily: "H.265",
    codecProfile: "HEVC",
    resolution: "3840×2160",
    fps: "23.98 fps",
    bitrate: "45 Mbps",
    size: "2.1 GB",
    status: "queued",
    preview: mediaPath("desert.png"),
    filePath: "/MEDIA/RAID/DesertAerial_SunrisePass_4K.mp4",
    colorSpace: "Rec. 2020",
    audio: "AAC 48kHz Stereo",
    sha256: "901fa2...c329",
  },
  {
    id: "night",
    name: "CityNight_TimeLapse_Final_v3.mp4",
    duration: "00:03:55:00",
    durationSeconds: 235,
    codec: "DNxHD 185x",
    codecFamily: "DNxHD",
    codecProfile: "185x",
    resolution: "1920×1080",
    fps: "25.00 fps",
    bitrate: "185 Mbps",
    size: "5.4 GB",
    status: "queued",
    preview: mediaPath("night.png"),
    filePath: "/MEDIA/RAID/CityNight_TimeLapse_Final_v3.mp4",
    colorSpace: "Rec. 709",
    audio: "PCM 48kHz 24b",
    sha256: "22b17d...9a31",
  },
  {
    id: "ocean",
    name: "OceanReef_Divemaster_POV.mov",
    duration: "00:14:20:08",
    durationSeconds: 860,
    codec: "ProRes 422",
    codecFamily: "PRRes",
    codecProfile: "422",
    resolution: "3840×2160",
    fps: "50.00 fps",
    bitrate: "160 Mbps",
    size: "17.2 GB",
    status: "queued",
    preview: mediaPath("ocean.png"),
    filePath: "/MEDIA/RAID/OceanReef_Divemaster_POV.mov",
    colorSpace: "Rec. 709",
    audio: "PCM 48kHz 24b",
    sha256: "f220c4...a1c8",
  },
  {
    id: "concert",
    name: "ConcertLive_MasterMix_5cam.mp4",
    duration: "01:32:00:00",
    durationSeconds: 5_520,
    codec: "H.264 (AVC)",
    codecFamily: "H.264",
    codecProfile: "AVC",
    resolution: "1920×1080",
    fps: "25.00 fps",
    bitrate: "20 Mbps",
    size: "13.4 GB",
    status: "queued",
    preview: mediaPath("concert.png"),
    filePath: "/MEDIA/RAID/ConcertLive_MasterMix_5cam.mp4",
    colorSpace: "Rec. 709",
    audio: "AAC 48kHz Stereo",
    sha256: "820da4...4e8b",
  },
];

export const initialBroadcastSettings: BroadcastSettings = {
  videoCodec: "H.265",
  profile: "High Profile",
  level: "5.1",
  preset: 18,
  width: 3840,
  height: 2160,
  dimensionsLocked: true,
  frameRate: "23.976 fps",
  deinterlace: false,
  fieldOrder: "progressive",
  rateControl: "VBR",
  targetBitrate: 18,
  maxBitrate: 24,
  bufferSize: 48_000,
  crf: 18,
  audioCodec: "AAC-LC",
  sampleRate: "48000 Hz",
  channels: "Stereo (L/R)",
  audioBitrate: 320,
  streamingEnabled: true,
  protocol: "SRT",
  serverUrl: "srt://stream.nexusbroadcast.live:4223",
  streamKey: "gruber-live-production-key",
  latency: "Low Latency",
  udpHost: "239.10.10.10",
  udpPort: 5000,
  udpPacketSize: 1316,
  udpTtl: 16,
  udpLocalAddress: "",
  udpServiceName: "FluxIO",
  udpServiceId: 1,
  udpProviderName: "FluxIO",
  udpVideoPid: 256,
  udpAudioPid: 257,
  udpServiceType: "digital_tv",
  udpPcrPeriodMs: 20,
  srtHost: "127.0.0.1",
  srtPort: 9000,
  srtMode: "caller",
  srtLatencyMs: 120,
  srtPassphrase: "",
  srtStreamId: "",
  rtmpServerUrl: "rtmp://127.0.0.1/live",
  rtmpStreamKey: "gruber-live",
  logoEnabled: false,
  logoPath: "",
  logoPosition: "top-right",
  logoWidthPercent: 15,
  logoMargin: 32,
  logoOpacity: 1,
  repeatSchedule: false,
  scte35PlanningEnabled: false,
  scte35Command: "time_signal + segmentation_descriptor",
  scte35Owner: "Provider",
  scte35Pid: 500,
  scte35PreRollMs: 4_000,
  scte35DefaultEventId: 1,
  scte35DefaultBreakDuration: 120,
  scte35UpidType: "Ad-ID",
  scte35DefaultUpid: "",
  scte35LoopEventStrategy: "Increment each loop",
};

export const encodingJobs: EncodingJob[] = [
  {
    id: "job-production",
    name: "Promo_BehindTheScenes_03_RAW.mov",
    progress: 78,
    eta: "ETA 00:03:14",
    bitrate: "18 Mbps",
  },
  {
    id: "job-interview",
    name: "Interview_President_Take02.mp4",
    progress: 12,
    eta: "ETA 01:42:10",
    bitrate: "18 Mbps",
  },
  {
    id: "job-reef",
    name: "GoPro_Undersea_Reef_HEVC.mp4",
    progress: 0,
    eta: "Queued",
    bitrate: "18 Mbps",
  },
];

export const filmstripImages = Array.from(
  { length: 8 },
  (_, index) =>
    mediaPath(`filmstrip-${String(index + 1).padStart(2, "0")}.png`),
);
